[{
    fullName: "Ariel Zissu",
    userName: "ariel",
    password: "123",
    isAdmin: true,
    bio: "Hello everyone, I played basketball",
    wishlist: [],
    imgUrl: `https://i.picsum.photos/id/542/200/250.jpg`,
    createdAt: 1521656526000,
}, {
    fullName: "Vlad Indikt",
    userName: "shuki",
    password: "shuki444",
    isAdmin: false,
    bio: "Hey my friends!!!",
    wishlist: [],
    imgUrl: `https://i.picsum.photos/id/552/200/250.jpg`,
    createdAt: 1490120526000,
}, {
    fullName: "Tamir Ben Simom",
    userName: "puki",
    password: "puki143",
    isAdmin: false,
    bio: "Nothing's better than a night of taki and paintings with my GF.",
    wishlist: [],
    imgUrl: `https://i.picsum.photos/id/562/200/250.jpg`,
    createdAt: 1426962126000,
},
]